server:
  port: 9100
  servlet:
    context-path: /pvs-api

webClient:
  baseUrl:
    sonar: "http://140.124.181.143:9002/api"
    test: ""
#
#logging:
#  config: classpath:log4j2.xml

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/PVS
    username: PVS
    password: lab1321
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Taipei

